config/routes.rb
Rails.application.routes.draw do
  resources :dashboard

  resources :locations do
    resources :votes
    
    member do
      post 'yay'
    end
  end

  root 'locations#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :votes

  obfuscate_id
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :location, counter_cache: true
  after_save :notify_pusher

  validates :location, presence: true

  obfuscate_id

  private

  def notify_pusher
    Pusher['dashboard'].trigger('update', {
      :vote_count => self.location.votes.count,
      :id => self.location.id
    })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
require 'csv'

class DashboardController < ApplicationController
  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"]

  def index
    @locations = Location.all.order('votes_count DESC')

    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"user-list\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"], except: [:index, :show, :yay]
  before_action :set_location, only: [:show, :edit, :update, :destroy, :yay]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @has_posted = cookies[:posted] || false
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @has_posted = cookies[:posted] || false
  end

  def yay
    @vote = @location.votes.build

    respond_to do |format|
      if @vote.save
        cookies[:posted] = { :value => true, :expires => 1.year.from_now }
        format.html { redirect_to location_vote_path(@location, @vote), notice: 'Thank you for voting!' }
      else
        format.html { redirect_to root_path, error: 'There was an error saving your vote. Contact EVfeedback@boston.gov if it continues.' }
      end
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :lat, :lng, :description)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def update
    @location = Location.find(params[:location_id])
    @vote = Vote.find(params[:id])

    if @vote.update(vote_params)
      cookies[:posted] = { :value => true, :expires => 1.year.from_now }
      redirect_to @location, notice: 'Thank you for voting!'
    else
      redirect_to @location, error: 'There was an error saving your vote. Contact EVfeedback@boston.gov if it continues.'
    end
  end

  def show
    @location = Location.find(params[:location_id])
    @vote = Vote.find(params[:id])
    @has_posted = cookies[:posted] || false
  end

  private

  def vote_params
    params.require(:vote).permit(:day, :time, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/dashboard/index.csv.erb
<%- headers = ['Location', 'Location ID', 'Preferred Day', 'Preferred Time', 'Comment'] -%>
<%= CSV.generate_line headers %>
<%- @locations.each do |location| -%>
  <%- location.votes.each do |vote| %>
    <%= CSV.generate_line([location.name, location.id, vote.day, vote.time, vote.comment]) -%>
  <%- end -%>
<%- end -%>

app/views/dashboard/index.html.erb
<div class="component component--centered component--small">
  <div class="component__title">
    <%= link_to "Download CSV", dashboard_path(:format => :csv) %>
    <h2>Vote totals</h2>
  </div>
  <ul class="dashboard">
    <% @locations.each do |location| %>
      <li id="location-<%= location.id %>" class="dashboard-item" data-votes="<%= location.votes_count %>">
        <span class="location__name"><%= location.name %></span>
        <span class="location__total"><%= location.votes_count %></span>
      </li>
    <% end %>
  </ul>
</div>

<script src="//js.pusher.com/2.2/pusher.min.js"></script>
<script>
  var pusher = new Pusher('<%= Pusher.key %>');
  var channel = pusher.subscribe('dashboard');

  channel.bind('update', function(data) {
    var el = $('#location-' + data.id);
    el.find('.location__total').text(data.vote_count || 0);
    el.data('votes', data.vote_count);

    $('body').trigger('sort_list');
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Vote for early voting locations</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBySQnQIwp0KZYhLiqVpnOFi-H_Bs8Su9s"></script>
  <link href='https://fonts.googleapis.com/css?family=Lora:400italic|Montserrat:700' rel='stylesheet' type='text/css'>
  <!--[if lte IE 9]>
    <%= javascript_include_tag 'flexibility', 'data-turbolinks-track' => true %>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
  <script src="//cob-header.herokuapp.com/header.js"></script>
  <footer class="footer" aria-role="hidden"></footer>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-2187282-29', 'auto');
  ga('send', 'pageview');

</script>
  <div id="google_translate_element"></div>
  <script type="text/javascript">
    function googleTranslateElementInit() {
      new google.translate.TranslateElement({pageLanguage: ['en', 'en-us'], autoDisplay: false}, 'google_translate_element');
    }
  </script>
  <script type="text/javascript" src="http://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Early voting dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <link href='https://fonts.googleapis.com/css?family=Lora:400italic|Montserrat:700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'dashboard', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="notice"><%= notice %></div>
  <%= yield %>
  <script src="//cob-header.herokuapp.com/header.js"></script>
  <footer class="footer" aria-role="hidden"></footer>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :description, "Address" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="header">
  <h1>City of Boston Early Voting Location Selection</h1>
</div>

<div class="component component--centered squiggle-border-bottom">
  <div class="component__title">
    <h2>Early Voting</h2>
  </div>
  <div class="component__intro">This fall, the City of Boston will be implementing early voting for the first time. Early voting is similar to absentee voting, however all residents are eligible to participate. From <strong>October 24 through November 4</strong>, you will be able to mail ballots to the Elections Department or vote at any early voting location around the City. Unlike traditional polling, you are not assigned to one location and can visit the location that is most convenient for you.</div>
</div>
<div class="component component--centered component--smallTop">
  <h3>Where and when do I vote?</h3>
  <p>Locations for early voting have not been decided. Unlike traditional voting, you are not assigned to a single polling location and can visit the early voting location that is most convenient for you.</p>
  <p>We're looking for input from residents on where to place early voting sites and what hours would be most convenient for residents—accessible from your home, on your lunch break, or while running errands.</p>
</div>


<div id="tableComponent" class="component component--centered">
  <div class="component__title">
    <h2>Voting Locations</h2>
  </div>
  <table>
    <thead>
      <th>Location Name</th>
      <th>Address</th>
    </thead>
    <tbody>
      <% @locations.each do |location| %>
        <tr class="location" data-lng="<%= location.lng %>" data-lat="<%= location.lat %>" data-template="#location-<%=location.id %>">
          <td><%= location.name %></td>
          <td><%= location.description %></td>
          <td><%= button_to 'This one', yay_location_path(location), {method: :post, class: 'btn btn-small btn-yay'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div aria-role="hidden" class="hidden">
  <% @locations.each do |location| %>
    <div class="location-template" id="location-<%=location.id %>">
      <h3>Would you like to vote for?</h3>
      <h4><%= location.name %></h4>
      <address><%= simple_format location.description %></address>
      <%= button_to 'This one', yay_location_path(location), {method: :post, class: 'btn btn-small btn-yay'} %>
    </div>
  <% end %>
</div>

<div class="map-container">
  <div class="map-modal">
    <div class="map-component component">
      <h3>Tell us where you want to vote</h3>
      <p>You can help us determine early voting sites by choosing a location that you would likely use. After selecting a site, you will be asked for days and times that you would prefer. This will not impact your regular polling location.</p>
      <p><em>Thank you for your interest. Voting has closed and we'll release an early voting schedule shortly.</em></p>
    </div>
  </div>
  <div id="map" class="hidden"></div>
</div>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<div class="header">
  <h1>City of Boston Early Voting Location Selection</h1>
  <div id="map" class="hidden"></div>
</div>

<div id="breadcrumb">
  <div class="breadcrumb">
    <%= link_to 'Location selection', root_path %><span class="crumbs-separator"> &gt; </span>Vote for <%= @location.name %>
  </div>
</div>

<div id="location" data-lat="<%= @location.lat %>" data-lng="<%= @location.lng %>" class="component component--centered">
  <div class="component__title">
    <h2><%= @location.name %></h2>
    <div class="component__location"><%= @location.description %></div>
  </div>
  <% if !@has_posted %>
    <div class="component__intro">
      Please <%= link_to "select a location", root_path %> to let us know your preferred voting location.
    </div>
  <% else %>
    <div class="component__intro">
      Thank you for letting us know that <%= @location.name %> is your preferred early voting location. If you have any feedback, please send an email to <a href="mailto:EVfeedback@boston.gov">EVfeedback@boston.gov</a>.
    </div>
  <% end %>
</div>

app/views/votes/show.html.erb
<div class="header">
  <h1>City of Boston Early Voting Location Selection</h1>
  <div id="map" class="hidden"></div>
</div>

<div id="breadcrumb">
  <div class="breadcrumb">
    <%= link_to 'Location selection', root_path %><span class="crumbs-separator"> &gt; </span>Vote for <%= @location.name %>
  </div>
</div>

<div id="location" data-lat="<%= @location.lat %>" data-lng="<%= @location.lng %>" class="component component--centered <% if !@has_posted %>squiggle-border-bottom<% end %>">
  <div class="component__title">
    <h2><%= @location.name %></h2>
    <div class="component__location"><%= @location.description %></div>
  </div>
  <div class="component__intro">
    You've selected <%= @location.name %> as your preferred early voting location. Now please let us know when would be most convenient for you to visit this location.
  </div>
</div>


<div class="component component--centered component--smallTop">
  <%= form_for [@location, @vote] do |f| %>
    <div class="form-item form-type-textfield form-item-name">
      <%= f.label :day, "Which day is most convenient?", class: 'block-label' %>
      <%= f.collection_radio_buttons :day, [['monday', 'Monday'], ['wednesday', 'Wednesday'], ['friday', 'Friday'], ['saturday', 'Saturday']], :first, :last do |b| %>
        <%= b.label class:"label-radio" do%>
          <%= b.radio_button %>
          <span class="outer"><span class="inner"></span></span>
          <span><%= b.text %></span>
        <%end%>
      <% end %>
    </div>
    <div class="form-item form-type-textfield form-item-name">
      <%= f.label :time, "What time of day is most convenient?", class: 'block-label' %>
      <%= f.collection_radio_buttons :time, [['early_morning', '7AM-10AM'], ['midday', '10AM-1PM'], ['afternoon', '1PM-4PM'], ['evening', '4PM-8PM']], :first, :last do |b| %>
        <%= b.label class:"label-radio" do%>
          <%= b.radio_button %>
          <span class="outer"><span class="inner"></span></span>
          <span><%= b.text %></span>
        <%end%>
      <% end %>
    </div>
    <div class="form-item form-type-textfield form-item-name">
      <%= f.label :comment, "Anything else you'd like us to know?", class: 'block-label' %>
      <%= f.text_field :comment, :class => "form-text", :size => 60, :maxlength => 200 %>
    </div>
    <%= f.button :class => "btn" do %>Submit your preferred times<% end %>
  <% end %>
</div>